### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Eisbaeeer** [SasaKaranovic/DIY-Camera-Slider#1]
Hi Sascha
Great project. I forked your project and Im interested to do some pull-requests for new features. Im wondering on wich license do you published your things. Are you able to add a license to allow pull-requests and e.g. mods for 3D-parts?
Thank you and greets
Lars

**Comment by SasaKaranovic** [comment]
Hi @Eisbaeeer, great question. I have added GNU GPLv3 license. Let me know if you have thoughts on that.

**Comment by Eisbaeeer** [comment]
Thanks!
