### ISSUE TITLE
Stepper driver replacement

### ISSUE THREAD

**Issue by leandromatos** [SasaKaranovic/DIY-Camera-Slider#12]
Can I replace the driver from DRV8825 with TMC2209? If yes, do I need to change something on the PCB?

**Comment by thijstriemstra** [comment]
I think @SasaKaranovic also uses TMC2209 in the instructions video. Zoom in on the video to get the correct driver orientation on the pcb. Also see [this comment](https://www.youtube.com/watch?v=-t66ZylGClk&lc=Ugwu3_leaV7w13GLg3t4AaABAg).
